//
// Generated file, do not edit! Created by nedtool 5.2 from Request.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __REQUEST_M_H
#define __REQUEST_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Request.msg:1</tt> by nedtool.
 * <pre>
 * packet Request
 * {
 *     char hostname[51];
 * }
 * </pre>
 */
class Request : public ::omnetpp::cPacket
{
  protected:
    char hostname[51];

  private:
    void copy(const Request& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Request&);

  public:
    Request(const char *name=nullptr, short kind=0);
    Request(const Request& other);
    virtual ~Request();
    Request& operator=(const Request& other);
    virtual Request *dup() const override {return new Request(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getHostnameArraySize() const;
    virtual char getHostname(unsigned int k) const;
    virtual void setHostname(unsigned int k, char hostname);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Request& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Request& obj) {obj.parsimUnpack(b);}


#endif // ifndef __REQUEST_M_H

