//
// Generated file, do not edit! Created by nedtool 5.2 from Response.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __RESPONSE_M_H
#define __RESPONSE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Response.msg:1</tt> by nedtool.
 * <pre>
 * packet Response
 * {
 *     char statuscode[8];
 *     int address;
 * }
 * </pre>
 */
class Response : public ::omnetpp::cPacket
{
  protected:
    char statuscode[8];
    int address;

  private:
    void copy(const Response& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Response&);

  public:
    Response(const char *name=nullptr, short kind=0);
    Response(const Response& other);
    virtual ~Response();
    Response& operator=(const Response& other);
    virtual Response *dup() const override {return new Response(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getStatuscodeArraySize() const;
    virtual char getStatuscode(unsigned int k) const;
    virtual void setStatuscode(unsigned int k, char statuscode);
    virtual int getAddress() const;
    virtual void setAddress(int address);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Response& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Response& obj) {obj.parsimUnpack(b);}


#endif // ifndef __RESPONSE_M_H

