//
// Generated file, do not edit! Created by nedtool 5.2 from ip/IPDatagram.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __IPDATAGRAM_M_H
#define __IPDATAGRAM_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../3rdParty/IPv4Address.h"
// }}

/**
 * Class generated from <tt>ip/IPDatagram.msg:8</tt> by nedtool.
 * <pre>
 * packet IPDatagram
 * {
 *     inet::IPv4Address destIP;
 *     inet::IPv4Address srcIP;
 *     short protocol;
 * }
 * </pre>
 */
class IPDatagram : public ::omnetpp::cPacket
{
  protected:
    inet::IPv4Address destIP;
    inet::IPv4Address srcIP;
    short protocol;

  private:
    void copy(const IPDatagram& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IPDatagram&);

  public:
    IPDatagram(const char *name=nullptr, short kind=0);
    IPDatagram(const IPDatagram& other);
    virtual ~IPDatagram();
    IPDatagram& operator=(const IPDatagram& other);
    virtual IPDatagram *dup() const override {return new IPDatagram(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual inet::IPv4Address& getDestIP();
    virtual const inet::IPv4Address& getDestIP() const {return const_cast<IPDatagram*>(this)->getDestIP();}
    virtual void setDestIP(const inet::IPv4Address& destIP);
    virtual inet::IPv4Address& getSrcIP();
    virtual const inet::IPv4Address& getSrcIP() const {return const_cast<IPDatagram*>(this)->getSrcIP();}
    virtual void setSrcIP(const inet::IPv4Address& srcIP);
    virtual short getProtocol() const;
    virtual void setProtocol(short protocol);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IPDatagram& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IPDatagram& obj) {obj.parsimUnpack(b);}


#endif // ifndef __IPDATAGRAM_M_H

